import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/ui/Header'
import { ThemeProvider } from '@/components/ui/ThemeProvider'
import ClientProviders from '@/components/ui/ClientProviders'
import Footer from '@/components/ui/Footer'
import FirebaseAuthProvider from '@/components/ui/FirebaseAuthProvider'
import SubscriptionProvider from '@/components/ui/SubscriptionProvider'
import { Toaster } from '@/components/ui/toaster'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClientProviders >
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <FirebaseAuthProvider>
        <SubscriptionProvider>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <Header />

        {children}

        <Toaster />

        <Footer />
        </ThemeProvider>
        </SubscriptionProvider>
        </FirebaseAuthProvider>
      </body>
    </html>
    </ClientProviders>
  )
}
